---
'':
  - ttl: 60
    type: A
    values:
      - 127.0.0.1
  - ttl: 3600
    type: NS
    values:
      - ns1.dns.dmcp.
      - ns2.dns.dmcp.
ns1:
  - ttl: 3600
    type: A
    values:
      - 127.0.0.1
ns2:
  - ttl: 3600
    type: A
    values:
      - 127.0.0.1
test:
  - ttl: 3600
    type: A
    values:
      - 127.0.0.1
test1:
  - ttl: 3600
    type: A
    values:
      - 1.2.3.4
