---
'':
  - ttl: 60
    type: A
    values:
      - 127.0.0.1
  - ttl: 3600
    type: NS
    values:
      - ns1.example.com.
      - ns2.example.com.
ns1:
  - ttl: 3600
    type: A
    values:
      - 127.0.0.1
ns2:
  - ttl: 3600
    type: A
    values:
      - 127.0.0.1
test:
  - ttl: 3600
    type: A
    values:
      - 127.0.0.1
