providers:
  config:
    class: octodns.provider.yaml.YamlProvider
    directory: OCTODNS_CONFIG_DIR
  powerdns:
    class: octodns.provider.powerdns.PowerDnsProvider
    host: localhost
    port: 8081
    api_key: test123
zones:
  example.com.:
    sources:
      - config
    targets:
      - powerdns
  dns.dmcp.:
    sources:
      - config
    targets:
      - powerdns
