name: OctoDNS Sync

on:
  push:
    paths:
      - 'config/production.yaml'
      - 'config/example.com.yaml'

jobs:
  octodns-sync:
    runs-on: [self-hosted]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: List contents of configs directory
        run: |
         ls -la configs/

      - name: Install dependencies
        run: |
          pip3 install -r requirements.txt  # using pip3 in case your system defaults pip to Python 2.x

      - name: Run OctoDNS sync
        env:
          OCTODNS_CONFIG_PATH: ${{ github.workspace }}/config/production.yaml
        run: |
          OCTODNS_CONFIG_PATH_ABSOLUTE="${{ github.workspace }}/configs/production.yaml"
          ~/dns/env/bin/octodns-sync --config=$OCTODNS_CONFIG_PATH_ABSOLUTE

          # If you have additional arguments or configurations, include them as needed here

      - name: Diagnostic output
        run: |
          which python3
          which pip3
