name: OctoDNS Sync

on:
  push:
    paths:
      - 'config/production.yaml'
      - 'config/example.com.yaml'

jobs:
  octodns-sync:
    runs-on: [self-hosted]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: List contents of config directory
        run: |
          ls -la config/

      - name: Install dependencies
        run: |
          pip3 install -r requirements.txt

      - name: Diagnostic output
        run: |
          which python3
          which pip3

      - name: Update OctoDNS config path
        run: |
          CONFIG_DIR="${{ github.workspace }}/config"  
          sed -i "s|OCTODNS_CONFIG_DIR|$CONFIG_DIR|g" $CONFIG_DIR/production.yaml

      - name: Run OctoDNS sync
        run: |
          OCTODNS_CONFIG_PATH_ABSOLUTE="${{ github.workspace }}/config/production.yaml"
          ~/dns/env/bin/octodns-sync --config=$OCTODNS_CONFIG_PATH_ABSOLUTE --doit
